name: tekartik_http_node
description: Http node
version: 0.6.0
publish_to: none

environment:
  sdk: '>=2.9.0-0 <3.0.0'

dependencies:
  tekartik_http:
    git:
      url: git://github.com/tekartik/http.dart
      path: http
      ref: dart2
    version: '>=0.6.0'
  tekartik_http_io:
    git:
      url: git://github.com/tekartik/http.dart
      path: http_io
      ref: dart2
    version: '>=0.6.0'
  node_interop: ">=1.0.3"
  node_io: '>=1.0.1+2'
  node_http: '>=1.0.0'
  meta: '>=1.2.3'

dev_dependencies:
  test: ">=1.5.2"
  dev_test: any
  build_runner: '>=1.7.0'
  build_test: '>=0.10.8'
  build_node_compilers: ">=0.2.2"
  tekartik_http_test:
    git:
      url: git://github.com/tekartik/http.dart
      path: http_test
      ref: dart2
    version: '>=0.1.0'
  tekartik_http_redirect:
    git:
      url: git://github.com/tekartik/http.dart
      path: http_redirect
      ref: dart2
    version: '>=0.1.0'
  tekartik_platform_node:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform_node
      ref: dart2
    version: '>=0.1.0'
  tekartik_app_node_build:
    git:
      url: git://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart2
    version: '>=0.2.3'
dependency_overrides:
#  tekartik_http:
#    path: ../http
#  tekartik_http_io:
#    path: ../http_io
#  tekartik_http_test:
#    path: ../http_test
#  tekartik_http_redirect:
#    path: ../http_redirect
