name: tekartik_http_test
description: Http test
version: 0.7.3
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
      ref: dart2_3
    version: '>=0.7.0'
  test:
dev_dependencies:
  dev_test: '>=0.15.0'
  process_run: '>=0.12.0'
  # build_runner: ">=0.9.0"
  build_test:

dependency_overrides:
  tekartik_http:
    path: ../http