name: tekartik_http_test
description: Http test
version: 0.7.3
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
      ref: dart3a
    version: '>=0.7.0'
  tekartik_http_io:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_io
      ref: dart3a
    version: '>=0.7.0'
  test:
  async:
  http:
  stream_channel:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
dev_dependencies:
  process_run: '>=0.12.0'
  # build_runner: ">=0.9.0"
  build_test:

resolution: workspace
