# Created with https://github.com/dart-lang/mono_repo
language: dart

sudo: required
addons:
  chrome: stable

before_install:
- nvm install node
- node --version

jobs:
  include:
    - stage: test
      script: dart ./tool/travis.dart
      dart: dev
    - stage: test
      script: dart ./tool/travis.dart
      dart: stable

stages:
  - test

cache:
  directories:
    - $HOME/.pub-cache

matrix:
  allow_failures:
    - dart: dev