name: tekartik_http_repo
description: Http repo (tools)
version: 0.1.0
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dev_dependencies:
  test: ">=1.2.0"
  dev_test: any
  grinder: any
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.3.4'
