name: tekartik_http
description: Http core
version: 0.7.6
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  http: '>=0.13.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
    version: '>=0.12.1'
  web_socket_channel: '>=2.0.0'

dev_dependencies:
  test: ">=1.24.0"
  process_run: ">=1.2.1+1"
resolution: workspace
