name: tekartik_http
description: Http core
version: 0.7.4
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: '>=0.13.0'
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: null_safety
    version: '>=0.12.1'
  web_socket_channel: '>=2.0.0'

dev_dependencies:
  test: '>=0.16.3'
  dev_test: '>=0.15.0'
  process_run: '>=0.12.0+1'
