name: tekartik_http
description: Http core
version: 0.2.0
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  http: any
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
  web_socket_channel: any

dev_dependencies:
  test: ">=0.12.37"
  dev_test: any
  build_runner: any

dependency_overrides:
  tekartik_http_test:
    path: ../http_test