name: tekartik_http
description: Http core
version: 0.7.5
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  http: '>=0.13.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.12.1'
  web_socket_channel: '>=2.0.0'

dev_dependencies:
  test: '>=0.16.3'
  process_run: '>=0.12.0+1'
