name: tekartik_http_browser
description: Http browser
version: 0.7.3
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
      ref: dart3a
  http:
dev_dependencies:
  process_run:
  test: ">=1.16.0"
  build_runner: '>=1.11.5'
  build_test: '>=0.10.8'
  build_web_compilers: '>=2.4.0'
  tekartik_http_test:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_test
      ref: dart3a

  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
dependency_overrides:
  tekartik_http:
    path: ../http
  tekartik_http_test:
    path: ../http_test
  web_socket_channel: any
