name: tekartik_http_redirect
description: A sample command-line application.
version: 0.7.2
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
      ref: dart3a
    version: '>=0.5.0'
  tekartik_http_io:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_io
      ref: dart3a
    version: '>=0.5.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  args: ">=2.6.0"
  process_run: ">=1.2.1+1"
  path: ">=1.9.0"
  http:

dev_dependencies:
  test: ">=1.24.0"
  build_test:
  # build_node_compilers: ">=0.2.2"
  # build_web_compilers: ">=0.4.2"

resolution: workspace
