name: tekartik_http_redirect
description: A sample command-line application.
version: 0.7.2
publish_to: none

environment:
  sdk: '>=2.12.0-259.15.beta <3.0.0'

dependencies:
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
      ref: dart2_3
    version: '>=0.5.0'
  tekartik_http_io:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_io
      ref: dart2_3
    version: '>=0.5.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
  args: '>=2.0.0'
  process_run:
  path:
  http:

dev_dependencies:
  dev_test: '>=0.15.0'
  test: '>=1.16.0'
  build_test:
  # build_node_compilers: ">=0.2.2"
  # build_web_compilers: ">=0.4.2"

dependency_overrides:
  tekartik_http:
    path: ../http
  tekartik_http_io:
    path: ../http_io
