name: tekartik_http_io
description: Http io
version: 0.7.4
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  path: ">=1.9.0"
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
      ref: dart3a
    version: '>=0.6.0'
  http:
dev_dependencies:
  test: ">=1.24.0"
  process_run: ">=1.2.1+1"
  tekartik_http_test:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_test
      ref: dart3a
    version: '>=0.6.0'

  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints

resolution: workspace
