name: tekartik_http_io
description: Http io
version: 0.5.5
publish_to: none

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  tekartik_http:
    git:
      url: git://github.com/tekartik/http.dart
      path: http
      ref: dart2
    version: '>=0.5.4'
  shelf: any

dev_dependencies:
  test: ">=1.2.0"
  dev_test: '>=0.13.2-dev.3'
  build_runner: ">=0.9.0"
  process_run: '>=0.10.0+1'

dependency_overrides:
  tekartik_http:
    path: ../http
  tekartik_http_test:
    path: ../http_test
