name: tekartik_http_io
description: Http io
version: 0.3.0+1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  dart2_constant: any
  tekartik_http:
    git:
      url: git://github.com/tekartik/http.dart
      path: http
      ref: dart2
    version: '>=0.3.0+1'
  shelf: any
dev_dependencies:
  test: ">=1.2.0"
  dev_test: any
  build_runner: ">=0.9.0"

dependency_overrides:
  tekartik_http:
    path: ../http
  tekartik_http_test:
    path: ../http_test
