name: tekartik_http_repo
description: Http repo (tools)
version: 0.5.2
publish_to: none

environment:
  sdk: '>=2.5.0 <3.0.0'

dev_dependencies:
  test: ">=1.2.0"
  dev_test: any
  # test dependencies without version
  tekartik_http_io:
    git:
      url: git://github.com/tekartik/http.dart
      ref: null_safety
      path: http_io
  tekartik_http_browser:
    git:
      url: git://github.com/tekartik/http.dart
      ref: null_safety
      path: http_browser

