name: tekartik_http_repo
description: Http repo (tools)
version: 0.5.2
publish_to: none

environment:
  sdk: ^3.9.0

dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints
  process_run: ">=1.2.1+1"
  path: ">=1.9.0"
_dev_dependencies:
  # test dependencies without version
  tekartik_http_io:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_io
  tekartik_http_browser:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_browser
resolution: workspace
