name: tekartik_http_repo
description: Http repo (tools)
version: 0.5.2
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ">=1.2.0"
  dev_test: any
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart2_3
      path: packages/lints
  process_run:
  path:
_dev_dependencies:
  # test dependencies without version
  tekartik_http_io:
    git:
      url: https://github.com/tekartik/http.dart
      ref: dart2_3
      path: http_io
  tekartik_http_browser:
    git:
      url: https://github.com/tekartik/http.dart
      ref: dart2_3
      path: http_browser

